Repository aufgabe3lab/MaraudersMap, pull requests merged in 2022-12, with the labels that each got.

#13 Enhancement branch login/register into development branch
  app/src/main/java/com/example/maraudersmap/LoginActivity.kt
  app/src/main/java/com/example/maraudersmap/RegisterActivity.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#14 Feature branch settings into development
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maraudersmap/SettingsActivity.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#15 feature-branch-backend-continuation into development
  app/src/main/java/com/example/maraudersmap/LocationXTO.kt
  app/src/main/java/com/example/maraudersmap/LoginActivity.kt
  app/src/main/java/com/example/maraudersmap/ServerCommunicator.kt
  app/src/main/java/com/example/maraudersmap/UserController.kt
  app/src/main/java/com/example/maraudersmap/UserXTO.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#16 Feature branch settings into development branch
  app/src/main/java/com/example/maraudersmap/LoginActivity.kt
  app/src/main/java/com/example/maraudersmap/MainActivity.kt
  app/src/main/java/com/example/maraudersmap/RegisterActivity.kt
  app/src/main/java/com/example/maraudersmap/SettingsActivity.kt
  app/src/main/java/com/example/maraudersmap/UserController.kt
  app/src/main/java/com/example/maraudersmap/UserXTO.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#18 Enhancement branch settings into development
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maraudersmap/LoginActivity.kt
  app/src/main/java/com/example/maraudersmap/MainActivity.kt
  app/src/main/java/com/example/maraudersmap/MapActivity.kt
  app/src/main/java/com/example/maraudersmap/RegisterActivity.kt
  app/src/main/java/com/example/maraudersmap/ServerCommunicator.kt
  app/src/main/java/com/example/maraudersmap/SettingsActivity.kt
  app/src/main/java/com/example/maraudersmap/UserController.kt
  app/src/main/java/com/example/maraudersmap/UserXTO.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#19 Bug branch backend into development
  app/src/main/java/com/example/maraudersmap/LocationXTO.kt
  app/src/main/java/com/example/maraudersmap/LoginActivity.kt
  app/src/main/java/com/example/maraudersmap/RegisterActivity.kt
  app/src/main/java/com/example/maraudersmap/ServerCommunicatorAPI.kt
  app/src/main/java/com/example/maraudersmap/SettingsActivity.kt
  app/src/main/java/com/example/maraudersmap/UserControllerAPI.kt
  app/src/main/java/com/example/maraudersmap/UserXTO.kt
  app/src/main/res/values/strings.xml
Labels: bug

#21 Feature branch autosendingposition into development
  app/src/main/java/com/example/maraudersmap/MapActivity.kt
  app/src/main/java/com/example/maraudersmap/SettingsActivity.kt
  app/src/main/java/com/example/maraudersmap/UserControllerAPI.kt
  app/src/main/res/layout/activity_settings.xml
Labels: bug, enhancement

#22 Bug branch settings into develpopment
  app/src/main/java/com/example/maraudersmap/MapActivity.kt
  app/src/main/java/com/example/maraudersmap/SettingsActivity.kt
  app/src/main/java/com/example/maraudersmap/UserControllerAPI.kt
  app/src/main/res/values/strings.xml
Labels: bug
